using UnityEngine;
using System.Collections;

public class InternetReachabilityChecker : MonoBehaviour {

	/// <summary>
	/// The localization key for the common message when internet is not reachable
	/// </summary>
	public const string INTERNET_NOT_AVAILABLE_KEY = "InternetConnectionRequired";

	protected static InternetReachabilityChecker _instance;
	public static InternetReachabilityChecker instance{
		get {
			if (_instance == null){
				_instance = FindObjectOfType<InternetReachabilityChecker>();
			}
			if (_instance == null){
				GameObject go = new GameObject("InternetReachabilityChecker_autogenerated");
				_instance = go.AddComponent<InternetReachabilityChecker>();
			}
			return _instance;
		}
	}

	public float delayBetweenChecks = 4f;
	public float timeout = 4f;
	private float nextCheck = float.NaN;

	public bool isInternetReachable
	{
		get;
		private set;
	}

	void Start()
	{
		nextCheck = Time.realtimeSinceStartup;
	}

	void Update () 
	{
		if (Time.realtimeSinceStartup >= nextCheck)
		{
			// Avoid other checks during the checking
			nextCheck = float.NaN;
			StartCoroutine(WebUtils.CheckInternetReachability((isReachable => { 
				isInternetReachable = isReachable;
				nextCheck = Time.realtimeSinceStartup + delayBetweenChecks;
			}), timeout));
		}
	}
}
